#
# JPAstreamer - Express JPA queries with Java Streams
# Copyright (c) 2020-2022, Speedment, Inc. All Rights Reserved.
#
# License: GNU Lesser General Public License (LGPL), version 2.1 or later.
#
# This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Lesser General Public License for more details.
#
# See: https://github.com/speedment/jpa-streamer/blob/master/LICENSE
#

site:
  title: JPAStreamer
  start_page: jpa-streamer:introduction:introduction.adoc
content:
  sources:
    - url: https://github.com/speedment/jpa-streamer
      # only generate from git tags (and not branches)
      branches: []
      start_path: docs
      tags: [0.1*, 1.0*, '!1.0.3', 1.1*, '!1.1.1']
ui:
  bundle:
    url: ui-bundle.zip
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files: [ .nojekyll ]
    - path: .nojekyll
asciidoc:
  attributes:
    page-pagination: true
output:
  dir: ../../jpa-streamer-gh-pages/jpa-streamer
